apiKeepAppy/config/routes.rb
Rails.application.routes.draw do
  
  
  

  devise_for :users

  match "/", :to => "sessions#home", via: [:get,:post]
  match "/setting", :to => "sessions#setting", via: [:get,:post]
  

  namespace :api, defaults: {format:'json'} do
    namespace :v1 do
      devise_for :users
      resources :base
      resources :registrations
      resources :quotes do
        collection do
          get :tag
        end
      end
      resources :articles do
        collection do
          get :tag
        end
      end
      resources :publicfeeds
    end
    
  end
  
  
  
  resources :publicfeeds

  resources :quotes do
    collection do
     get :tag
    end
  end

  resources :articles do
    collection do
      get :tag
    end
  end

 

  
  

end

apiKeepAppy/app/models/quote.rb
class Quote < ActiveRecord::Base
  acts_as_taggable
end

apiKeepAppy/app/controllers/api/v1/quotes_controller.rb
module Api
  module V1
    class QuotesController < ApplicationController

      class Quote < ::Quote
        # Note: this does not take into consideration the create/update actions for changing released_on
        def as_json(options = {})
          super.merge(tags: tag_list)  #appends tag_list to the api json object
        end
      end
      ##user auth
      #before_filter :authenticate_user!
      respond_to :json
      #articles.json should be returned, but is returning old json object
      def index
        if params[:tag]
          respond_with Quote.tagged_with(params[:tag])
        else
          respond_with Quote.all
        end
      end
      def tag
        respond_with Quote.tagged_with(params[:tag])
      end

      private
      def set_article
        @article = Quote.find(params[:id])
      end

      def quote_params
      params.require(:quote).permit(:cite, :progenitor, :classification, :tag_list)
    end
    end
  end
end

apiKeepAppy/app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_quote, only: [:show, :edit, :update, :destroy]
 # load_and_authorize_resource

  # GET /quotes
  # GET /quotes.json
  def index
    if params[:tag]
      @quotes = Quote.tagged_with(params[:tag])
    else
      @quotes = Quote.all
    end
  end
  def tag
    @quotes = Quote.tagged_with(params[:tag])
    render :action => 'index'
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:cite, :progenitor, :classification, :tag_list)
    end
end

apiKeepAppy/app/helpers/quotes_helper.rb
module QuotesHelper
end

apiKeepAppy/app/views/quotes/_form.html.erb
<%= javascript_include_tag "quote.js" %>

<head xmlns="http://www.w3.org/1999/html"><link rel="stylesheet" type="text/scss" href="quotes/quote_form.scss"></head>
<div class="frm">
<%= form_for(@quote) do |f| %>
    <% if @quote.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

          <ul>
            <% @quote.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :cite %><br>
      <%= f.text_area :cite %>
    </div>
    <div class="field" >
      <%= f.label :progenitor %><br>
      <%= f.text_field :progenitor %>
    </div>
    <div class="field">
      <%= f.label :tag_list, "Tags (seperated by commas)" %><br />
      <%= f.text_field :tag_list %>
    </div>
    <div class="field">
      <%= f.label :classification %><br>
      <%= f.number_field :classification %>
    </div>
    <div class="actions butn">
      <%= f.submit %>
    </div>
<% end %>
</div>
<div class="bck_btn">
<p class="btn-orange-arrow"><%= link_to 'Back', quotes_path %></p>
</div>

apiKeepAppy/app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render 'form' %>
<!-- insert show button -->

apiKeepAppy/app/views/quotes/index.html.erb
<head><link rel="stylesheet" type="text/scss" href="quotes/quote_index.scss"></head>
<h1>Listing quotes</h1>
<div class="row"><button class="button button1">
  <% if can? :create, @quote %>
     <%= link_to 'New Quote', new_quote_path %>
  <% end %>
</button>
<button class="button button1"><%= link_to "Back to Home", controller: "sessions", action: "home"  %></button>
<a href="/home"></a></div>

<h3>Click on a quote for more options</h3>

    <% @quotes.each do |quote| %>
      <blockquote class="quote-card yellow-card" data-toggle="collapse" data-target="#<%= quote.id%>">
        <p>
          <%= quote.cite %>
        </p>
        <cite>
          <%= quote.progenitor %>
        </cite>
        <p>
        <strong>Tags:</strong>
        <%= raw quote.tag_list.map{ |t| link_to t, :controller=>"quotes", :action=>"tag", :tag => t }.join(', ') %>
        </p>

        
      </blockquote>
      <div id="<%= quote.id%>" class="panel-collapse collapse">
        <div class="panel-body">
          <div class="row">
            <p class="btn btn-primary"><%= link_to 'Show', quote %></p>
            <p class="btn btn-primary"> 
              <% if can? :update, @quote %>
                <%= link_to ' Edit', edit_quote_path(quote) %>
              <% end %>
	         </p>
            <p class="btn btn-primary">  
              <% if can? :delete, @quote %>
                <%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
          </p>
          </div>
        </div>
      </div>

    <% end %>


<br>

apiKeepAppy/app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render 'form' %>

apiKeepAppy/app/views/quotes/show.html.erb
<blockquote class="quote-card" data-toggle="collapse" data-target="#<%= @quote.id%>">
  <p>
    <%= @quote.cite %>
  </p>
  <cite>
    <%= @quote.progenitor %>
  </cite>
  <p>
    <strong>Tags:</strong>
    <%= raw @quote.tag_list.map{ |t| link_to t, :controller=>"quotes", :action=>"tag", :tag => t }.join(', ') %>
  </p>


</blockquote>
<div id="<%= @quote.id%>" class="panel-collapse collapse">
  <div class="panel-body">
    <div class="row">
      <p class="btn btn-primary">
        <% if can? :update, @quote %>
            <%= link_to ' Edit', edit_quote_path(@quote) %>
        <% end %>
      </p>
      <p class="btn btn-primary">
        <%if can? :delete, @quote %>
            <%= link_to 'Destroy', @quote, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </p>
    </div>
  </div>
</div>

<% if can? :update, @quote %>
    <%= link_to 'Edit', edit_quote_path(@quote) %>
<% end %> |
<%= link_to 'Back', quotes_path %>