apiKeepAppy/config/routes.rb
Rails.application.routes.draw do
  
  
  

  devise_for :users

  match "/", :to => "sessions#home", via: [:get,:post]
  match "/setting", :to => "sessions#setting", via: [:get,:post]
  

  namespace :api, defaults: {format:'json'} do
    namespace :v1 do
      devise_for :users
      resources :base
      resources :registrations
      resources :quotes do
        collection do
          get :tag
        end
      end
      resources :articles do
        collection do
          get :tag
        end
      end
      resources :publicfeeds
    end
    
  end
  
  
  
  resources :publicfeeds

  resources :quotes do
    collection do
     get :tag
    end
  end

  resources :articles do
    collection do
      get :tag
    end
  end

 

  
  

end

apiKeepAppy/app/models/publicfeed.rb
class Publicfeed < ActiveRecord::Base
end

apiKeepAppy/app/controllers/api/v1/publicfeeds_controller.rb
module Api
  module V1
    class PublicfeedsController < ApplicationController
      respond_to :json
      ##user auth
      #before_filter :authenticate_user!
      def index
        respond_with Publicfeed.all
      end
      
      private
      # Use callbacks to share common setup or constraints between actions.
      def set_publicfeed
        @publicfeed = Publicfeed.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def publicfeed_params
        params.require(:publicfeed).permit(:title,:content, :rate)
      end
    end
  end
end

apiKeepAppy/app/controllers/publicfeeds_controller.rb
class PublicfeedsController < ApplicationController
  before_filter :authenticate_user! 
  before_action :set_publicfeed, only: [:show, :edit, :update, :destroy]
  #load_and_authorize_resource #checks roll permissions of User
  # GET /publicfeeds
  # GET /publicfeeds.json
  def index
    @publicfeeds = Publicfeed.all 
  end

  # GET /publicfeeds/1
  # GET /publicfeeds/1.json
  def show
  end

  # GET /publicfeeds/new
  def new
    @publicfeed = Publicfeed.new
  end

  # GET /publicfeeds/1/edit
  def edit
  end

  # POST /publicfeeds
  # POST /publicfeeds.json
  def create
    @publicfeed = Publicfeed.new(publicfeed_params)

    respond_to do |format|
      if @publicfeed.save
        format.html { redirect_to @publicfeed, notice: 'Publicfeed was successfully created.' }
        format.json { render :show, status: :created, location: @publicfeed }
      else
        format.html { render :new }
        format.json { render json: @publicfeed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publicfeeds/1
  # PATCH/PUT /publicfeeds/1.json
  def update
    respond_to do |format|
      if @publicfeed.update(publicfeed_params)
        format.html { redirect_to @publicfeed, notice: 'Publicfeed was successfully updated.' }
        format.json { render :show, status: :ok, location: @publicfeed }
      else
        format.html { render :edit }
        format.json { render json: @publicfeed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publicfeeds/1
  # DELETE /publicfeeds/1.json
  def destroy
    @publicfeed.destroy
    respond_to do |format|
      format.html { redirect_to publicfeeds_url, notice: 'Publicfeed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publicfeed
      @publicfeed = Publicfeed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publicfeed_params
      params.require(:publicfeed).permit(:title,:content, :rate)
    end
end

apiKeepAppy/app/helpers/publicfeeds_helper.rb
module PublicfeedsHelper
end

apiKeepAppy/app/views/publicfeeds/_form.html.erb
<head xmlns="http://www.w3.org/1999/html"><link rel="stylesheet" type="text/scss" href="pubFeed/pubFeed_form.scss"></head>
<div class="pb_frm">
<%= form_for(@publicfeed) do |f| %>
  <% if @publicfeed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publicfeed.errors.count, "error") %> prohibited this publicfeed from being saved:</h2>

      <ul>
      <% @publicfeed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
  </div>
<div class="bck_btn">
  <p class="btn-pnk-arrow"><%= link_to 'Back', publicfeeds_path %></p>
</div>

apiKeepAppy/app/views/publicfeeds/edit.html.erb
<h1>Editing publicfeed</h1>

<%= render 'form' %>

<!-- insert show button -->

apiKeepAppy/app/views/publicfeeds/index.html.erb
<h1>Listing publicfeeds</h1>
<div class="row"><button class="button button1">
	<% if can? :create, @publicfeed %>
		<%= link_to 'New Post', new_publicfeed_path %></button>
  	<% end %>
<button class="button button1"><%= link_to "Back to Home", controller: "sessions", action: "home"  %></button>
  <a href="/home"></a></div>
<h3>Click on a post for more options</h3>
<ul class="activity-stream">
    <% @publicfeeds.each do |publicfeed| %>
      <li data-toggle="collapse" data-target="#<%= publicfeed.id%>"><i class="fa fa-user icon fa-3x"></i>
        <h4 class="titl"><b><%= publicfeed.title %></b></h4>
        <cite><%= publicfeed.content %> </cite>
      </li>
      <div id="<%= publicfeed.id%>" class="panel-collapse collapse">
        <div class="panel-body">
          <div class="row">
            <p class="btn btn-primary"><%= link_to 'Show', publicfeed %></p>

            <p class="btn btn-primary">
            <% if can? :update, @publicfeed %>
                  <%= link_to ' Edit', edit_publicfeed_path(publicfeed) %>
              <% end %> 
            </p>
            <p class="btn btn-primary"> 
            <% if can? :delete, @publicfeed %>
                  <%= link_to 'Destroy', publicfeed, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %><
            </p>
          </div>
        </div>
      </div>
    <% end %>
</ul>
<br>

apiKeepAppy/app/views/publicfeeds/new.html.erb
<h1>New publicfeed</h1>

<%= render 'form' %>

<%= link_to 'Back', publicfeeds_path %>

apiKeepAppy/app/views/publicfeeds/show.html.erb
<div class="post" data-toggle="collapse" data-target="#<%= @publicfeed.id%>" ><i class="fa fa-user icon fa-5x"></i>
  <p class="titl"><b><%= @publicfeed.title %></b></p>
  <p><%= @publicfeed.content %> </p>
</div>
<div id="<%= @publicfeed.id%>" class="panel-collapse collapse">
  <div class="panel-body">
    <div class="row">

      <p class="btn btn-primary"><% if can? :update, @quote %>
            <%= link_to ' Edit', edit_publicfeed_path(@publicfeed) %>
        <% end %></p>
      <p class="btn btn-primary">  <%= link_to 'Destroy', @publicfeed, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    </div>
  </div>
</div>

<%= link_to 'Back', publicfeeds_path %>